stages:
 - build
 - test

cache:
 paths:
   - .m2/repository
 key: "$CI_JOB_NAME"

variables:
  MAVEN_OPTS: "-Dsun.net.client.defaultConnectTimeout=30000 -Dsun.net.client.defaultReadTimeout=30000"

before_script:
  - apk add --no-cache curl
  - until curl -sSf https://repo.maven.apache.org/maven2/; do echo "Waiting for Maven repository to be available..."; sleep 5; done

build_job:
  stage: build
  image: eclipse-temurin:17-jdk-alpine
  script:
    - echo "Testing network connectivity..."
    - curl -v https://repo.maven.apache.org/maven2/
    - ./mvnw compile
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=true

test_job:
  stage: test
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw test
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
